CREATE TABLE car (
    listing_id VARCHAR(50) PRIMARY KEY,
    vin VARCHAR(50),
    make VARCHAR(100),
    model VARCHAR(100),
    year INTEGER,
    condition VARCHAR(30),
    mpg_city INTEGER,
    mpg_highway INTEGER,
    fuel_type VARCHAR(50),
    mileage INTEGER,
    number_of_doors INTEGER,
    engine VARCHAR(200),
    interior_color VARCHAR(50),
    transmission VARCHAR(100),
    cars_rating REAL,
    exterior_color VARCHAR(50),
    city VARCHAR(100),
    state VARCHAR(100),
    zip_code CHAR(5),
    advanced_details JSONB,
    price REAL
);